### PR TITLE
Fixes #10: adds support for composer 2.x.

### LINKED ISSUE #10: Support Composer 2.x

### PR DESCRIPTION
**Pull request by mikemadison13**

### CODE REVIEW

**Comment by danepowell** [comment]
Looks like there was already a work in progress for this? https://github.com/grasmash/drupal-security-warning/pull/8

**Comment by mikemadison13** [comment]
yeah, there is, but it also changes quite a bit of other stuff and hasn't been touched in a bit, so i wanted to try and do something as simple as possible

**Comment by mohammadzo** [comment]
Hey guys, I can see still composer 2.0 is complaining about version 1.1.1 .

```The "grasmash/drupal-security-warning" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.1.0"). You may need to run composer update with the "--no-plugins" option.```


`$ composer info  grasmash/drupal-security-warning
The "grasmash/drupal-security-warning" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.1.0"). You may need to run composer update with the "--no-plugins" option.
name     : grasmash/drupal-security-warning
descrip. : Warns users installing Drupal project versions not supported by Security Team.
keywords : drupal, security
versions : * 1.1.1`

**Comment by danepowell** [comment]
I think @grasmash needs to issue a new stable release

**Pull request merged**
